MAX_LEN_STRING = 0xFFFF
MAX_ID = 0x3FFFFF
MAX_DEPTH = 0x3FF
MAX_NUM_GLOBAL_VARIABLES = 0xFFFF
MAX_NUM_LOCAL_VARIABLES = 0x7FFFF
MAX_FUNC_PARAMETERS = 0xFF
MAX_STRUCT_MEMBERS = 0x3FFF
MAX_STRUCT_DEPTH = 0xFF
